version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - provider

  provider:
    build:
      context: ./provider
      dockerfile: Dockerfile
    ports:
      - 5000:5000